# Generated by Django 4.0.4 on 2022-07-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='marketAddress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='marketName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='market_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store'),
        ),
    ]
