# Generated by Django 4.0.4 on 2022-07-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_user_user_profile_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='address',
        ),
    ]
