# Generated by Django 4.0.4 on 2022-07-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_user_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='marketName',
        ),
    ]
