# Generated by Django 4.0.4 on 2022-07-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_marketaddress_user_profile_market_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
