# Generated by Django 4.0.4 on 2022-07-10 17:46

from django.db import migrations, models
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('data_create', models.DateField()),
                ('capital', models.BigIntegerField()),
                ('purchases', models.BigIntegerField()),
            ],
        ),
    ]
