# Generated by Django 4.0.4 on 2022-07-10 19:19

from django.db import migrations, models
import django.db.models.deletion
import product.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=product.models.get_file_path)),
                ('unit_name', models.CharField(max_length=50)),
                ('selling_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('has_list', models.BooleanField(default=False)),
                ('list_name', models.CharField(blank=True, max_length=50)),
                ('list_amount', models.BigIntegerField()),
                ('listselling_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
                ('quantityInStore', models.BigIntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
