# Generated by Django 4.0.4 on 2022-07-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
