# Generated by Django 4.0.4 on 2022-07-22 08:00

import Category.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=Category.models.get_file_path)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
            ],
        ),
    ]
