# Generated by Django 4.0.4 on 2022-07-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='purchas_price',
            field=models.FloatField(blank=True),
        ),
    ]
