# Generated by Django 4.0.4 on 2022-07-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_purchas_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
