# Generated by Django 4.0.4 on 2022-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_cart_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='purchas_price',
            field=models.DecimalField(decimal_places=10, max_digits=50),
        ),
    ]
