# Generated by Django 4.0.4 on 2022-07-16 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('purchas_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('sellin_price', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('selling_price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('num_list', models.IntegerField()),
                ('list_amount', models.IntegerField()),
                ('list_selling', models.BigIntegerField()),
                ('purchase_price', models.BigIntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
