# Generated by Django 4.0.4 on 2022-07-22 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('Store', '0001_initial'),
        ('profiles', '0006_alter_user_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('purchas_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('sellin_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.user_profile')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('selling_price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('num_list', models.IntegerField()),
                ('list_amount', models.IntegerField()),
                ('list_selling', models.BigIntegerField()),
                ('purchase_price', models.BigIntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
